version: '3.4'

services:
  rinha.db:
    image: postgres:latest
    container_name: rinha.database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local